CREATE TABLE IF NOT EXISTS reward_discipline (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL, -- KHEN_THUONG, KY_LUAT
    amount DECIMAL(15,2) DEFAULT 0,
    reason TEXT,
    effective_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE
);

ALTER TABLE bang_luong ADD COLUMN tien_thuong DECIMAL(15,2) DEFAULT 0;
ALTER TABLE bang_luong ADD COLUMN tien_phat DECIMAL(15,2) DEFAULT 0;
